version: '3'
services:
  db:
    build:
      context: docker/db
      dockerfile: Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./docker/db/mysql_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        SERVER_NAME: ${SERVER_NAME}
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./:/app
      - ./docker/web/php.ini:/usr/local/etc/php/php.ini
    networks:
      - default
    depends_on:
        - db
    command: /bin/bash /app/docker/web/entrypoint.sh

